"""Replace the archived reference site's imagery and metadata with Kernellum's."""

from pathlib import Path
import re

DOCS = Path(__file__).resolve().parents[1] / "docs"
path = DOCS / "index.html"
html = path.read_text(encoding="utf-8")

# The archived SSR markup contains image URLs at three resolutions. All art is
# first-party and generated by generate_site_art.py instead of fetched at runtime.
art = [
    ("architecture-die", "Architecture search die with routed interconnect"),
    ("route-topology", "Routed signal topology"),
    ("timing-field", "Timing field and physical traces"),
    ("measurement-array", "Implementation measurement array"),
    ("route-topology", "Routed interconnect map"),
    ("timing-field", "Timing signal visualization"),
    ("measurement-array", "Physical implementation measurements"),
    ("architecture-die", "Architecture die study"),
]
counter = 0


def replace_image(match: re.Match) -> str:
    global counter
    if counter >= len(art):
        return match.group(0)
    name, alt = art[counter]
    counter += 1
    priority = ' fetchpriority="high"' if counter == 1 else ' loading="lazy"'
    return (
        f'<img src="/kernellum/assets/{name}.svg" width="1600" height="1100" '
        f'alt="{alt}" style="object-fit:cover;object-position:50% 50%;opacity:1;"'
        f'{priority} data-v-9eed875e>'
    )


html = re.sub(r"<img\b[^>]*>", replace_image, html)
assert counter == 8, f"Expected eight content images, found {counter}"
html = re.sub(r'<link rel="preconnect" href="https://cdn\.sanity\.io"[^>]*>', "", html)
html = re.sub(r'<link rel="preload" as="image"[^>]*>', "", html)
html = re.sub(r'<link rel="(?:icon|shortcut icon|apple-touch-icon|manifest)"[^>]*>', "", html)
html = html.replace('<meta name="google-site-verification" content="BTlOzEkTP4agdbyUQQVH', '<meta name="unused-verification" content="BTlOzEkTP4agdbyUQQVH')
html = re.sub(r'<meta name="unused-verification"[^>]*>', "", html)
html = html.replace('<title>Kernellum</title>', '<title>Kernellum | Architecture search grounded in physical evidence</title>')
html = html.replace('content="Cause The Effect"', 'content="Kernellum | Architecture search grounded in physical evidence"')
html = re.sub(r'<meta property="og:image"[^>]*>', '<meta property="og:image" content="https://sushxnthd.github.io/kernellum/assets/architecture-die.svg">', html)
html = html.replace('https://www.boonglobal.io/', 'https://sushxnthd.github.io/kernellum/')
html = html.replace('content="Boon"', 'content="Kernellum"')
html = html.replace('<link rel="stylesheet" href="/kernellum/runtime.css?v=14">',
                    '<link rel="icon" type="image/svg+xml" href="/kernellum/assets/favicon.svg"><link rel="stylesheet" href="/kernellum/runtime.css?v=15">')
html = html.replace('/kernellum/runtime.js?v=28', '/kernellum/runtime.js?v=29')
# The old hydration payload refers to the reference site's API and is unused by
# our standalone runtime. Removing it avoids a misleading third-party identity.
html = re.sub(r'<script type="application/json" data-nuxt-data=.*?</script>', '', html, flags=re.S)
html = re.sub(r'<script type="application/ld\+json".*?</script>',
    '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization","name":"Kernellum","url":"https://sushxnthd.github.io/kernellum/","sameAs":"https://github.com/sushxnthd/kernellum"}</script>', html, flags=re.S)
# Replace the SSR fallback logo, which otherwise shows the reference brand
# before JS starts. The runtime provides the same wordmark in the active header.
html = re.sub(r'(<a\b[^>]*aria-label=")Boon("[^>]*>).*?(</a>)',
    r'\1Kernellum\2<svg viewBox="0 0 89 24" role="img" aria-label="Kernellum"><text x="44.5" y="16.8" text-anchor="middle" fill="currentColor" font-family="Space Grotesk, sans-serif" font-size="11.4" font-weight="600" letter-spacing=".35">KERNELLUM</text></svg>\3', html, flags=re.S)
path.write_text(html, encoding="utf-8")

for name, title, desc in [
    ("what-we-do", "What We Do", "Architecture search informed by routed physical-design evidence."),
    ("who-we-are", "Who We Are", "The research principles behind Kernellum."),
    ("careers", "Careers", "Explore the open research and engineering work at Kernellum."),
    ("contact", "Contact", "Discuss Kernellum research, reproduction, and collaboration."),
]:
    page = DOCS / name / "index.html"
    text = page.read_text(encoding="utf-8")
    text = text.replace('<title>Kernellum</title>', f'<title>{title} | Kernellum</title><meta name="description" content="{desc}"><link rel="icon" type="image/svg+xml" href="../assets/favicon.svg">')
    text = text.replace('multipage.css?v=8', 'multipage.css?v=9').replace('multipage.js?v=8', 'multipage.js?v=9')
    page.write_text(text, encoding="utf-8")
